import json

from sklearn.externals import joblib

classifier = joblib.load('category_mapping/data/pickles/factualNameCategory.pkl')
factual_tax_json = open('category_mapping/data/factual_taxonomy.json', 'r')

vtax = ["Peach Orthodontics: Peach Karl D DDS",
    "Olympia Hills Golf & Event Center",
    "Capsulenet LLC",
    "DWV Plumbing Inc",
    "Visiting Angels Living Assistance Services",
    "Painted Mountain Golf Club",
    "Reliable Garage Door",
    "Hamden-Shreline Oral Surgery: Parker Robert DDS",
    "Chino Valley Pediatric Dentistry",
    "Interstate National",
    "Dr. Andrew G. Pullinger DDS",
    "Chief Fire Systems",
    "Wyatt Richard L",
    "Borealis Window Cleaning",
    "Grab N Go Deli",
    "TD Bank",
    "Advanced Collision Service",
    "Visiting Angels",
    "Care Resource / Dr. Klara Gershman, MD",
    "Pittsburgh Cut Flower Co",
    "Sun Valley Gardens",
    "Villa D'Aqua",
    "Certified Auto",
    "Ascend Performance Materials",
    "Southern Oregon Dental Health: Chatfield Jeremy DDS",
    "Payday Express",
    "Allegra.ca Marketing Print Web - Vancouver - False Creek",
    "Peerless Maximizer",
    "Family Flooring",
    "Friars Wings of Hernando",
    "Glass Doctor",
    "Brodie Dental LLC",
    "Jersey Mikes Subs 3rd Ave",
    "Arborist Services LLC",
    "Advanced Therapy Specialist",
    "Dr. Harvey J. Elerson Jr",
    "Otero Alfred DDS",
    "The Hamptons at Research Triangle Park",
    "Vivian Kwon DDS",
    "Clarkson Self Storage",
    "Donovan Data Systems",
    "Charlotte Family Housing",
    "Inland Perio Dr. Daniel M. Kunihira Dr. Dan Newbold and Dr. Mark Kunihira",
    "Rocky Mountain Oral X-Ray",
    "Tanna Orthodontics",
    "Capital Estates",
    "Good Feet Store",
    "S&S Heating And Cooling",
    "Riverview Family Dental PC",
    "Sabine Pools & Spas",
    "Abba Monument Co",
    "Ashland Family Dentistry - Drs Layer Beck and Cullen",
    "Bodywaves,Inc.",
    "Embroidery By Ellen",
    "Waterford Place",
    "SmileRite Family Dentistry",
    "Big Valley Sanitation",
    "Chandler Dentist - Jeffrey S. Garelick DDS",
    "Artistic Orthodontics",
    "Addison Dental Group",
    "Donald E Finch PC",
    "Davis Dental Family and Cosmetic Dentistry",
    "Acadiana Transmission",
    "Joe Cannon DDS",
    "Paul Brooks Noland D.M.D.",
    "Supervac Of Lincoln",
    "Mazda of Manchester",
    "Marlborough Family Dental PC",
    "Observer Park",
    "Times Square Pizzeria (Walmart)",
    "Times Square Pizzeria (Walmart)",
    "Timothy Woods",
    "Red Rock Catering",
    "Affordable Stump Grinding",
    "Northlake Glass",
    "UNITED FRAMING COMPANY, INC.",
    "Grier's Roofing & Construction",
    "ADC Dental Clinic Inc",
    "PARKone",
    "Piedras Preciosas del Reino",
    "Carpet World",
    "Marketplace America",
    "Memorial Health Credit Union",
    "Black Lake Apartments",
    "Minoa Estates Apartments",
    "Lion's Den Efficiency Apartments",
    "Won-A-Go Biking",
    "Jakes Pour House",
    "Midwest Retail Services",
    "H & H Chevrolet",
    "Rice Funeral Services",
    "Kansas City Urology Care",
    "Kareismatic LLC",
    "Estancia at Morningstar",
    "Parker S C & Co Inc",
    "Nader Dayani",
    "Toro Bowl Bistro and Bar",
    "Airport Limousine",
    "Michelle B. Deutch D.D.S.",
    "Midnight Sun Martial Arts Academy",
    "The Kitchen Shop",
    "Tanya L. DeSanto DDS",
    "Fossil Creek Dental",
    "Open Up Garage Door Inc",
    "Pamela G. Doray, DMD",
    "General Surgery Clinics: Doyle John F DDS",
    "Fresco 57",
    "New Image Roofing Houston",
    "Lambeth House",
    "Whitlow Dental Care",
    "Conwell Isotalo Insurance Services",
    "Daisy Dooks",
    "J & S Portable Toilets",
    "Suter Orthodontics",
    "Advanced Back Care",
    "Gannon, Timothy E Photography Inc",
    "Las Vegas Dental Experts - Dr. Harvey H Chin DDS",
    "The Bristol",
    "East Springs Family Dentistry: Clark Anthony DDS",
    "Savarese & Company",
    "Pusch Ridge Stables",
    "Haven at Avalon",
    "Jefferson Neurobehavioral Group",
    "Jefferson Neurobehavioral Group",
    "ServPro of West Corvina",
    "Towne Square",
    "Bliss by Arctic Spas",
    "Dr. David Casagrande, DDS - Billings, MT",
    "Todd's Nursery",
    "Above & Beyond Roofing LLC",
    "Bridgeport Dental Partners",
    "Oregon Family Dental PC",
    "Admirals Cove Apartments",
    "WK Pilates",
    "Affordable Dentures: Benson Dawn J DDS",
    "Laura Giese DDS",
    "Foschi Photography",
    "Lansdale Surveyg Inc",
    "BREATHE DAY SPA AND SALON",
    "Cross Creek",
    "Ohle & Ohle",
    "Midway Electric Inc",
    "Hallmac RV Rentals",
    "Wilson's Towing",
    "Gonzales Animal Clinic",
    "Face and Jaw Surgery Center",
    "Priority One Courier Inc",
    "Alamex",
    "Jefferson Townhouses",
    "Encantada At Dove Mountain",
    "Villa Del Rio Apartments",
    "Glass Doctor of Burlington",
    "Carmel Canyon",
    "Will's Jewelers Inc",
    "Callahan & Son Plumbing & Septic",
    "Steven K. Okamoto DDS",
    "Lake Village",
    "Sugar Creek Brewing Company",
    "Garage Solutions",
    "Arrowhead Creekside Dental",
    "Modern Closets",
    "Augusta Cooperative Farm Bureau, Inc.",
    "Greater Rochester Orthopaedics",
    "Olde World Jewelers",
    "Dalton Heating & Cooling Incorporated",
    "Meadowrun",
    "Orbisonia Hardware",
    "Ironfish",
    "County Dental at Fishkill",
    "United Way of Citrus County",
    "James S. Vaughan D.D.S.",
    "Westbrook Crossing",
    "Lieutenants Run",
    "Summit Dental Group Southwest",
    "DEMARCHE CONSULTING GROUP, INC",
    "Bay Climate Control Inc",
    "KY International Inc",
    "ServiceMaster of Willimantic",
    "Las Villas",
    "Add Value International Inc. o/a GoMobileAppsSolutions.com",
    "Temp Coat",
    "Tom Hunter Septic Tank Service Inc.",
    "Exceptional Dentistry",
    "Bailey Creek Apartments",
    "One Jefferson Parkway",
    "Unknown company",
    "Charlotte's Magic Movers",
    "Cosmetology Training Center",
    "Julles Posh Food Co",
    "Georgetown Village",
    "Desert Gastroenterology: Rivera Steven T DDS",
    "Rancho Carrera",
    "Integrity Carpets",
    "Levine Meredith DDS",
    "Willamette Dental Group: Wagner Charles A DDS",
    "Justin Haase Excavating",
    "Western Extermination Services",
    "The Best of NY Food",
    "Massage Heights Edmonton Mayfield",
    "Don's Sports Cards",
    "Marathon Painters",
    "Oral Facial Pain Center",
    "Zeko's Pizzeria And Grill",
    "Hermitage Garden Apartments",
    "Loma Linda University School-Dentistry: Park Chan M DDS",
    "College Hunks Hauling Junk - Tampa, FL",
    "Anna's Flowers & Gifts",
    "Boca Raton Condominium",
    "Parminter Paul DDS",
    "Rosenlicht and Ansari Oral Facial Implant Surgery Center",
    "Kelley Thomas DDS",
    "Salon Modeles LLC",
    "Stephen Wagner DDS PC",
    "Roger Densley DDS PLLC",
    "Cheyenne Mountain Dental Group",
    "A Dental Care 24Hrs - A Group of Shamlian Dental",
    "Living Free From Diabetes",
    "Family and Cosmetic Dentistry of Fairfield",
    "Augusta Center for Health & Rehabilitation",
    "Villere's Florist",
    "Cafe Oliviero",
    "Southwest RV Park",
    "Dr. Raymond Cros DMD",
    "Carrizales Law Offices",
    "Cafe Lafayette",
    "Colonies North Dental Care",
    "John W. Inga D.D.S. Ltd.",
    "Robert M Miller Inc",
    "Elite Dentistry: Dr Mark Ashy and Dr Chris Chard",
    "Life -Insurance-All Major National Providers",
    "Prospect Promos/Printing",
    "Whispering Lake",
    "Vig's Health Food Store",
    "Absolute Seamless Gutters and Patio Enclosures",
    "Dr. Coulter T. Crowley DDS",
    "Westside Endodontic Pros Ltd",
    "The Harris Family Law Firm",
    "Dr. Christine L. Lamarre DDS",
    "Dub Li Inc",
    "Beverly Hills Cosmetic Dental: Boyajian A J DDS",
    "Clean Community System",
    "dyna body by lee",
    "Pulliam Innovative Consulting Firm",
    "Highland Park Periodontics and Dental Implants PLLC",
    "The Greens West",
    "All Around Fence Co",
    "Dr. Ronald K. Wagner DDS",
    "Kellie Burke Interiors",
    "Fantastic Sam's",
    "Lakeland Family Dental",
    "Tuesday Morning",
    "The Preserve Apartments",
    "Dr. Aaron D. Johnson DMD The Smile Center",
    "New York Design",
    "L M Rojas Dental",
    "Woodall's Pump Sales & Service",
    "Quiet Zone"
        ]

factual_tax = json.load(factual_tax_json)

predicted = classifier.predict(vtax)

for vt, category in zip(vtax, predicted):
    print('%s => %s - %s' % (vt, category, factual_tax[str(category)]["labels"]["en"]))

